language: php

branches:
  # Only test the master branch and SemVer tags.
  only:
    - master
    - /^[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+.*$/

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0

sudo: false

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

before_script:
  - 'if [ "$TRAVIS_PHP_VERSION" = "5.4" ]; then composer require "phpdocumentor/reflection-docblock:^2.0"; fi'
  - composer install

script:
  - vendor/bin/phpcs --standard=PSR2 -n src
  - vendor/bin/phpunit

after_success:
  - travis_retry php vendor/bin/coveralls -v
